package io.nexora.catalog.interfaces.rest.v1.dto;

import io.nexora.shared.valueobject.Money;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Currency;
import java.util.UUID;

/**
 * DTO for creating a new product.
 * Note: No ID here; it's generated by the system.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CreateProductRequest {
    @NotEmpty(message = "Name cannot be left empty")
    @Size(min = 2, message = "Name must be at least 2 characters long")
    private String name;

    private String description;

    @NotNull(message = "Price must be provided")
    private BigDecimal amount;

    @NotNull(message = "Currency must be provided")
    private Currency currency;

    @Min(value = 0, message = "Stock quantity cannot be negative")
    private int stockQuantity;

    @NotNull(message = "Category ID must be provided")
    private UUID categoryId;


}